period:
  start_date: "2000-01-01T00:00:00"
  end_date: "2024-12-01T00:00:00"

fastapi:
  debug: True,
  title: "EnviroData API"
  version: "2.0.1"
  description: "This is the OpenAPI documentation for the current development of the EnviroData project by the Chair of Model-Based Environmental Exposure Science"
  contact:
      name": "MBEES EnviroData API"
      url": "https://mbees.med.uni-augsburg.de/"
  license_info:
      name: "License"
      url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
  openapi_url: "/openapi.json"
  swagger_ui_parameters: {"syntaxHighlight.theme": "obsidian"}

uvicorn:
  host: 0.0.0.0
  port: 8000
  log_level: trace

geocoder:
  url: "http://nominatim:8080/search.php"

environment:
  domain:
    lonmin: &lonmin 8.9
    lonmax: &lonmax 13.9
    latmin: &latmin 47.2
    latmax: &latmax 50.6
  services:
    - label: "DWD"
      metadata: "services/DWD"
      input:
        module: "envirodata.services.dwd"
        config: {}
      output:
        module: "envirodata.services.dwd"
        config:
          api_url: "http://brightsky-web-1:5000/weather"
    - label: "AirBASE"
      metadata: "services/AirBASE"
      input:
        module: "envirodata.services.airbase"
        config:
          cache_path: &AIRBASE_CACHE_PATH "cache/airbase/"
          pollutants: [ "CO", "O3", "NO2", "SO2", "NH3", "PM1", "PM2.5", "PM10", "HCHO" ]
          countries: &AIRBASE_COUNTRY_LIST [ "DE" ]
          bbox: [ *lonmin, *latmin, *lonmax, *latmax ]
      output:
        module: "envirodata.services.airbase"
        config:
          cache_path: *AIRBASE_CACHE_PATH
    - label: "Noise_mapping"
      metadata: "services/Noise_mapping"
      input:
        module: "envirodata.services.geotiff"
        config:
          data_table:
            #"NOISE_DAY": "/Users/knotechr/Projects/mams/data/environment/noise/NOISE_DAY.tif"
            "NOISE_DAY": "https://megastore.rz.uni-augsburg.de/get/KivxMoRMeC/"
            #"NOISE_NIGHT": "/Users/knotechr/Projects/mams/data/environment/noise/NOISE_NIGHT.tif"
            "NOISE_NIGHT": "https://megastore.rz.uni-augsburg.de/get/PqxfqgZVk8/"
          cache_path: &NOISE_CACHE_PATH "cache/noise/"
      output:
        module: "envirodata.services.geotiff"
        config:
          cache_path: *NOISE_CACHE_PATH
    - label: "Destatis"
      metadata: "services/Destatis"
      input:
        module: "envirodata.services.destatis"
        config:
          db_url: &DESTATIS_DB_URL "sqlite:///cache/Destatis.sqlite3"
          csv_paths: 
            #"Durchschnittsalter": "/Users/knotechr/Downloads/Durchschnittsalter_in_Gitterzellen/Zensus2022_Durchschnittsalter_100m-Gitter.csv"
            "Durchschnittsalter": "https://megastore.rz.uni-augsburg.de/get/HA4L46wkBb/"
            #"Einwohner": "/Users/knotechr/Downloads/Zensus2022_Bevoelkerungszahl/Zensus2022_Bevoelkerungszahl_100m-Gitter.csv"
            "Einwohner": "https://megastore.rz.uni-augsburg.de/get/LwxXATa3FL/"
            #"durchschnMieteQM": "/Users/knotechr/Downloads/Zensus2022_Durchschn_Nettokaltmiete/Zensus2022_Durchschn_Nettokaltmiete_100m-Gitter.csv"
            "durchschnMieteQM": "https://megastore.rz.uni-augsburg.de/get/hAy4HJhGfQ/"
      output:
        module: "envirodata.services.destatis"
        config:
          db_url: *DESTATIS_DB_URL
