period:
  start_date: "2024-01-01T00:00:00"
  end_date: "2024-02-01T00:00:00"

geocoder:
  url: "http://localhost:8080/search.php"

environment:
  domain:
    lonmin: &lonmin 8.9
    lonmax: &lonmax 13.9
    latmin: &latmin 47.2
    latmax: &latmax 50.6
  services:
    - label: "DWD"
      variables:
        - "precipitation"
        - "pressure_msl"
        - "sunshine"
        - "temperature"
        - "wind_direction"
        - "wind_speed"
        - "cloud_cover"
        - "dew_point"
        - "relative_humidity"
        - "visibility"
        - "wind_gust_direction"
        - "wind_gust_speed"
      input:
        module: "envirodata.services.dwd"
        config: {}
      output:
        module: "envirodata.services.dwd"
        config:
          api_url: "http://localhost:5000/weather"
          statistics:
            precipitation:
              - day_sum
            pressure_msl:
              - current
              - 24h_max_3h_delta
              - 5day_max_3h_delta
            sunshine:
              - day_sum
            temperature:
              - current
              - 24h_amplitude
              - 3day_mean_day_max
              - 3day_max_day_max
              - 3day_mean_day_min
              - 3day_min_day_min
              - 7day_mean_day_max
              - 7day_max_day_max
              - 7day_mean_day_min
              - 7day_min_day_min            
            wind_direction:
              - current
            wind_speed:
              - current
              - 3day_mean
              - 7day_mean
            cloud_cover:
              - current
            dew_point:
              - current
            relative_humidity:
              - current
              - 24h_amplitude
              - 3day_mean_day_max
              - 3day_max_day_max
              - 3day_mean_day_min
              - 3day_min_day_min
              - 7day_mean_day_max
              - 7day_max_day_max
              - 7day_mean_day_min
              - 7day_min_day_min
            visibility:
              - current
            wind_gust_direction:
              - current
            wind_gust_speed:
              - current
              - 3day_mean
              - 7day_mean
    - label: "AirBASE"
      variables: [ "CO", "O3", "NO2", "SO2", "NH3", "HCHO", "PM1", "PM2.5", "PM10" ]
      input:
        module: "envirodata.services.airbase"
        config:
          cache_path: &AIRBASE_CACHE_PATH "cache/airbase/"
          pollutants: [ "CO", "O3", "NO2", "SO2", "NH3", "PM1", "PM2.5", "PM10", "HCHO" ]
          countries: &AIRBASE_COUNTRY_LIST [ "DE" ]
          bbox: [ *lonmin, *latmin, *lonmax, *latmax ]
      output:
        module: "envirodata.services.airbase"
        config:
          cache_path: *AIRBASE_CACHE_PATH
          variable_translation_table:
            "CO": "CO" 
            "O3": "O3" 
            "NO2": "NO2"
            "SO2": "SO2"
            "NH3": "NH3"
            "HCHO": "HCHO"
            "PM1": "PM1"
            "PM2.5": "PM2.5"
            "PM10": "PM10"
          statistics:
            CO:
              - current
              - day_mean
              - day_max
              - 3day_mean
              - 3day_max
              - 7day_mean
              - 7day_max
            O3:
              - current
              - mda8
              - 3day_mean_mda8
              - 7day_mean_mda8
              - day_min
              - day_mean
              - day_max
              - 3day_min
              - 3day_mean
              - 3day_max
              - 7day_min
              - 7day_mean
              - 7day_max
            NO2:
              - current
              - day_mean
              - day_max
              - 3day_mean
              - 3day_max
              - 7day_mean
              - 7day_max
            PM2.5:
              - current
              - day_mean
              - day_max
              - 3day_mean
              - 3day_max
              - 7day_mean
              - 7day_max
            PM10:
              - current
              - day_mean
              - day_max
              - 3day_mean
              - 3day_max
              - 7day_mean
              - 7day_max
    - label: "Noise_mapping"
      variables: [ "NOISE_DAY", "NOISE_NIGHT" ]
      input:
        module: "envirodata.services.geotiff"
        config:
          data_table:
            "NOISE_DAY": "/Users/knotechr/Projects/mams/data/environment/noise/NOISE_DAY.tif"
            "NOISE_NIGHT": "/Users/knotechr/Projects/mams/data/environment/noise/NOISE_NIGHT.tif"
          cache_path: &NOISE_CACHE_PATH "cache/noise/"
      output:
        module: "envirodata.services.geotiff"
        config:
          cache_path: *NOISE_CACHE_PATH
          statistics:
            NOISE_DAY:
              - current
            NOISE_NIGHT:
              - current
