period:
  start_date: "2024-01-01T00:00:00"
  end_date: "2024-02-01T00:00:00"

geocoder:
  url: "http://localhost:8080/search.php"

environment:
  domain:
    lonmin: &lonmin 8.9
    lonmax: &lonmax 13.9
    latmin: &latmin 47.2
    latmax: &latmax 50.6
  services:
    - label: "DWD"
      variables:
        - "precipitation"
        - "pressure_msl"
        - "sunshine"
        - "temperature"
        - "wind_direction"
        - "wind_speed"
        - "cloud_cover"
        - "dew_point"
        - "relative_humidity"
        - "visibility"
        - "wind_gust_direction"
        - "wind_gust_speed"
      input:
        module: "envirodata.services.dwd"
        config: {}
      output:
        module: "envirodata.services.dwd"
        config:
          api_url: "http://localhost:5000/weather"
          statistics:
            precipitation:
              - day_sum
            pressure_msl:
              - current
              - 24h_max_3h_delta
              - 5day_max_3h_delta
            sunshine:
              - day_sum
            temperature:
              - current
              - 24h_amplitude
              - 3day_mean_day_max
              - 3day_max_day_max
              - 3day_mean_day_min
              - 3day_min_day_min
              - 7day_mean_day_max
              - 7day_max_day_max
              - 7day_mean_day_min
              - 7day_min_day_min            
            wind_direction:
              - current
            wind_speed:
              - current
              - 3day_mean
              - 7day_mean
            cloud_cover:
              - current
            dew_point:
              - current
            relative_humidity:
              - current
              - 24h_amplitude
              - 3day_mean_day_max
              - 3day_max_day_max
              - 3day_mean_day_min
              - 3day_min_day_min
              - 7day_mean_day_max
              - 7day_max_day_max
              - 7day_mean_day_min
              - 7day_min_day_min
            visibility:
              - current
            wind_gust_direction:
              - current
            wind_gust_speed:
              - current
              - 3day_mean
              - 7day_mean
    - label: "AirBASE"
      variables: [ "CO", "O3", "NO2", "SO2", "NH3", "HCHO", "PM1", "PM2.5", "PM10" ]
      input:
        module: "envirodata.services.airbase"
        config:
          cache_path: &AIRBASE_CACHE_PATH "cache/airbase/"
          pollutants: [ "CO", "O3", "NO2", "SO2", "NH3", "PM1", "PM2.5", "PM10", "HCHO" ]
          countries: &AIRBASE_COUNTRY_LIST [ "DE" ]
          bbox: [ *lonmin, *latmin, *lonmax, *latmax ]
      output:
        module: "envirodata.services.airbase"
        config:
          cache_path: *AIRBASE_CACHE_PATH
          variable_translation_table:
            "CO": "CO" 
            "O3": "O3" 
            "NO2": "NO2"
            "SO2": "SO2"
            "NH3": "NH3"
            "HCHO": "HCHO"
            "PM1": "PM1"
            "PM2.5": "PM2.5"
            "PM10": "PM10"
          statistics:
            CO:
              - current
              - day_mean
              - day_max
              - 3day_mean
              - 3day_max
              - 7day_mean
              - 7day_max
            O3:
              - current
              - mda8
              - 3day_mean_mda8
              - 7day_mean_mda8
              - day_min
              - day_mean
              - day_max
              - 3day_min
              - 3day_mean
              - 3day_max
              - 7day_min
              - 7day_mean
              - 7day_max
            NO2:
              - current
              - day_mean
              - day_max
              - 3day_mean
              - 3day_max
              - 7day_mean
              - 7day_max
            PM2.5:
              - current
              - day_mean
              - day_max
              - 3day_mean
              - 3day_max
              - 7day_mean
              - 7day_max
            PM10:
              - current
              - day_mean
              - day_max
              - 3day_mean
              - 3day_max
              - 7day_mean
              - 7day_max
    - label: "Noise_mapping"
      variables: [ "NOISE_DAY", "NOISE_NIGHT" ]
      input:
        module: "envirodata.services.geotiff"
        config:
          data_table:
            "NOISE_DAY": "/Users/knotechr/Projects/mams/data/environment/noise/NOISE_DAY.tif"
            "NOISE_NIGHT": "/Users/knotechr/Projects/mams/data/environment/noise/NOISE_NIGHT.tif"
          cache_path: &NOISE_CACHE_PATH "cache/noise/"
      output:
        module: "envirodata.services.geotiff"
        config:
          cache_path: *NOISE_CACHE_PATH
          statistics: {}
    - label: "CAMS"
      variables: [ "PM2.5", "O3", "NO2"]
      input:
        module: "envirodata.services.cdsapi"
        config:
          dataset: "cams-europe-air-quality-forecasts"
          request:
            model: "ensemble"
            date: "%Y-%m-%d/%Y-%m-%d"
            format: "netcdf"
            variable: [
                "nitrogen_dioxide",
                "ozone",
                "particulate_matter_2.5um"
            ]
            level: "0"
            type: "analysis"
            time: [
                '00:00', '01:00', '02:00', '03:00', '04:00', '05:00',
                '06:00', '07:00', '08:00', '09:00', '10:00', '11:00',
                '12:00', '13:00', '14:00', '15:00', '16:00', '17:00',
                '18:00', '19:00', '20:00', '21:00', '22:00', '23:00',
            ]
            leadtime_hour: "0"
            area: [ *latmax, *lonmin, *latmin, *lonmax ]
          output_fpath_pattern: &CAMS_CACHE_PATH_PATTERN "cache/cams/%Y%m%d.nc"
          # cdsurl: ...
          # cdskey: ...
      output:
        module: "envirodata.services.cdsapi"
        config:
          cache_fpath_pattern: *CAMS_CACHE_PATH_PATTERN
          time_calculation: "time_since_analysis"
          variable_translation_table:
            "PM2.5": "pm2p5_conc"
            "NO2": "no2_conc"
            "O3": "o3_conc"
          statistics:
            NOISE_DAY:
              - current
            NOISE_NIGHT:
              - current
    - label: "ERA5_land"
      variables: [ "U_10m", "V_10m", "Td_2m", "T_2m" ]
      input:
        module: "envirodata.services.cdsapi"
        config:
          dataset: "reanalysis-era5-land"
          request:
            variable: [
                '10m_u_component_of_wind', 
                '10m_v_component_of_wind', 
                '2m_dewpoint_temperature',
                '2m_temperature',
            ]
            year: '%Y'
            month: '%m'
            day: '%d'
            time: [
                '00:00', '01:00', '02:00', '03:00', '04:00', '05:00',
                '06:00', '07:00', '08:00', '09:00', '10:00', '11:00',
                '12:00', '13:00', '14:00', '15:00', '16:00', '17:00',
                '18:00', '19:00', '20:00', '21:00', '22:00', '23:00',
            ]
            area: [ *latmax, *lonmin, *latmin, *lonmax ]
            format: 'netcdf'
          output_fpath_pattern: &ERA5_LAND_CACHE_PATH_PATTERN "cache/era5_land/%Y%m%d.nc"
          # cdsurl: ...
          # cdskey: ...
      output:
        module: "envirodata.services.cdsapi"
        config:
          cache_fpath_pattern: *ERA5_LAND_CACHE_PATH_PATTERN
          time_calculation: "hours_since_epoch"
          variable_translation_table:
            "U_10m": "u10"
            "V_10m": "v10"
            "Td_2m": "d2m"
            "T_2m":  "t2m"
          statistics: {}
