period:
  start_date: "2000-01-01T00:00:00"
  end_date: "2024-12-01T00:00:00"

fastapi:
  debug: True,
  title: "EnviroData API"
  version: "2.0.1"
  description: "This is the OpenAPI documentation for the current development of the EnviroData project by the Chair of Model-Based Environmental Exposure Science"
  contact:
      name": "MBEES EnviroData API"
      url": "https://mbees.med.uni-augsburg.de/"
  license_info:
      name: "License"
      url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
  openapi_url: "/openapi.json"
  swagger_ui_parameters: {"syntaxHighlight.theme": "obsidian"}

uvicorn:
  host: 0.0.0.0
  port: 8000
  log_level: trace

geocoder:
  url: "http://localhost:8080/search.php"

environment:
  domain:
    lonmin: &lonmin 8.9
    lonmax: &lonmax 13.9
    latmin: &latmin 47.2
    latmax: &latmax 50.6
  services:
    - label: "DWD"
      metadata: "services/DWD"
      input:
        module: "envirodata.services.dwd"
        config: {}
      output:
        module: "envirodata.services.dwd"
        config:
          api_url: "http://localhost:5000/weather"
    - label: "AirBASE"
      metadata: "services/AirBASE"
      input:
        module: "envirodata.services.airbase"
        config:
          cache_path: &AIRBASE_CACHE_PATH "cache/airbase/"
          pollutants: [ "CO", "O3", "NO2", "SO2", "NH3", "PM1", "PM2.5", "PM10", "HCHO" ]
          countries: &AIRBASE_COUNTRY_LIST [ "DE" ]
          bbox: [ *lonmin, *latmin, *lonmax, *latmax ]
      output:
        module: "envirodata.services.airbase"
        config:
          cache_path: *AIRBASE_CACHE_PATH
    - label: "Noise_mapping"
      metadata: "services/Noise_mapping"
      input:
        module: "envirodata.services.geotiff"
        config:
          data_table:
            #"NOISE_DAY": "/Users/knotechr/Projects/mams/data/environment/noise/NOISE_DAY.tif"
            "NOISE_DAY": "https://megastore.rz.uni-augsburg.de/get/KivxMoRMeC/"
            #"NOISE_NIGHT": "/Users/knotechr/Projects/mams/data/environment/noise/NOISE_NIGHT.tif"
            "NOISE_NIGHT": "https://megastore.rz.uni-augsburg.de/get/PqxfqgZVk8/"
          cache_path: &NOISE_CACHE_PATH "cache/noise/"
      output:
        module: "envirodata.services.geotiff"
        config:
          cache_path: *NOISE_CACHE_PATH
    - label: "Destatis"
      metadata: "services/Destatis"
      input:
        module: "envirodata.services.destatis"
        config:
          db_url: &DESTATIS_DB_URL "sqlite:///cache/Destatis.sqlite3"
          csv_paths: 
            "Durchschnittsalter": "/Users/knotechr/Downloads/Durchschnittsalter_in_Gitterzellen/Zensus2022_Durchschnittsalter_100m-Gitter.csv"
            "Einwohner": "/Users/knotechr/Downloads/Zensus2022_Bevoelkerungszahl/Zensus2022_Bevoelkerungszahl_100m-Gitter.csv"
            "durchschnMieteQM": "/Users/knotechr/Downloads/Zensus2022_Durchschn_Nettokaltmiete/Zensus2022_Durchschn_Nettokaltmiete_100m-Gitter.csv"
      output:
        module: "envirodata.services.destatis"
        config:
          db_url: *DESTATIS_DB_URL
    - label: "CAMS"
      metadata: "services/CAMS"
      input:
        module: "envirodata.services.cdsapi"
        config:
          dataset: "cams-europe-air-quality-forecasts"
          request:
            model: "ensemble"
            date: "%Y-%m-%d/%Y-%m-%d"
            format: "netcdf"
            variable: [
                "nitrogen_dioxide",
                "ozone",
                "particulate_matter_2.5um"
            ]
            level: "0"
            type: "analysis"
            time: [
                '00:00', '01:00', '02:00', '03:00', '04:00', '05:00',
                '06:00', '07:00', '08:00', '09:00', '10:00', '11:00',
                '12:00', '13:00', '14:00', '15:00', '16:00', '17:00',
                '18:00', '19:00', '20:00', '21:00', '22:00', '23:00',
            ]
            leadtime_hour: "0"
            area: [ *latmax, *lonmin, *latmin, *lonmax ]
          output_fpath_pattern: &CAMS_CACHE_PATH_PATTERN "cache/cams/%Y%m.nc"
          # cdsurl: ...
          # cdskey: ...
          dataset_start_date: "2022-01-01 00:00:00"
          #dataset_end_date: "2024-01-01 00:00:00"
      output:
        module: "envirodata.services.cdsapi"
        config:
          cache_fpath_pattern: *CAMS_CACHE_PATH_PATTERN
          time_calculation: "time_since_analysis"


