var: "air_temperature"
t_interval: "10_minutes"  # ['10_minutes','hourly']
state: ["Bayern"]  # state is a list, wrapped in []
target_folder: "../../0.raw/dwd"
year_start: 2010
year_end: 2022


output:
  dbname:
  dbuser:
  dbpw:
  ...
input:
  - era5:
      download_url: ...
      variables:
        - temperature:
          config: {}
        - relative_humidity:
          config: {... calc from dew point ...}
